package com.ics.utils.importexcelfile;

import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author nateelive
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/ics/utils/importexcelfile/Excel-icon.png")).getImage());
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        DatabaseConnection.connect();
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                DatabaseConnection.disconnect();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDocumentNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDocDate = new javax.swing.JTextField();
        btnLoadFile = new javax.swing.JButton();
        btnDateDialog = new javax.swing.JButton();
        cbChangeTheme = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lbDisplayTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFileData = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ข้อมูลเอกสาร", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("เลขที่เอกสาร (S_NO)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("วันที่สร้าง");

        btnLoadFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLoadFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ics/utils/importexcelfile/Excel-icon.png"))); // NOI18N
        btnLoadFile.setText("เลือกไฟล์สำหรับ Upload");
        btnLoadFile.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLoadFile.addActionListener(this::btnLoadFileActionPerformed);

        btnDateDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ics/utils/importexcelfile/Calendar-icon.png"))); // NOI18N
        btnDateDialog.addActionListener(this::btnDateDialogActionPerformed);

        cbChangeTheme.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cbChangeTheme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FlatLightLaf", "FlatDarkLaf" }));
        cbChangeTheme.addItemListener(this::cbChangeThemeItemStateChanged);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("เลือก Template");

        lbDisplayTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDisplayTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbDisplayTotal.setText("จำนวนทั้งหมด 0 แถว");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLoadFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDocumentNo)
                    .addComponent(txtDocDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDateDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 536, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbChangeTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbDisplayTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtDocumentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbChangeTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDocDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDateDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbDisplayTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbFileData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data"
            }
        ));
        jScrollPane1.setViewportView(tbFileData);

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ics/utils/importexcelfile/icons8-save-32.png"))); // NOI18N
        btnSave.setText("บันทึกเอกสาร");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Import Excel / Menu Items");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("เลือกอัปโหลดไฟล์ Excel เพื่อดูข้อมูลสินค้า");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Application Version: 1.0:0.0.1_ Copy Right @ ICS 2026");

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ics/utils/importexcelfile/icons8-cancel-32.png"))); // NOI18N
        btnExit.setText("ปิดโปรแกรม (Close)");
        btnExit.addActionListener(this::btnExitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFileActionPerformed
        loadFiles();
    }//GEN-LAST:event_btnLoadFileActionPerformed

    private void btnDateDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateDialogActionPerformed
        showDateSelected();
    }//GEN-LAST:event_btnDateDialogActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveDataIntoDatabase();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbChangeThemeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbChangeThemeItemStateChanged
        changeThemeApp();
    }//GEN-LAST:event_cbChangeThemeItemStateChanged

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        closeApplication();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    private static void applyThaiFont() {
        // FlatLaf bundles "Inter" font which has no Thai glyphs.
        // Override defaultFont with Tahoma which ships with every Windows version and supports Thai.
        javax.swing.UIManager.put("defaultFont",
            new javax.swing.plaf.FontUIResource("Tahoma", java.awt.Font.PLAIN, 13));
    }

    public static void main(String args[]) {
        LoggerSetup.init();

        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.WARNING, "FlatLaf unavailable, using default L&F", ex);
        }

        applyThaiFont();

        // Rounded corners & accent color (must be set after setup)
        javax.swing.UIManager.put("Button.arc",          10);
        javax.swing.UIManager.put("Component.arc",        8);
        javax.swing.UIManager.put("TextComponent.arc",    6);
        javax.swing.UIManager.put("ScrollBar.thumbArc", 999);
        javax.swing.UIManager.put("ScrollBar.trackArc",  999);
        javax.swing.UIManager.put("Component.accentColor", new java.awt.Color(0x2196F3));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDateDialog;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbChangeTheme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDisplayTotal;
    private javax.swing.JTable tbFileData;
    private javax.swing.JTextField txtDocDate;
    private javax.swing.JTextField txtDocumentNo;
    // End of variables declaration//GEN-END:variables

    private void loadFiles() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Excel Files (*.xlsx)", "xlsx"));
        fileChooser.setAcceptAllFileFilterUsed(false);

        int result = fileChooser.showOpenDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File selectedFile = fileChooser.getSelectedFile();

        try (FileInputStream fis = new FileInputStream(selectedFile);
             Workbook workbook = new XSSFWorkbook(fis)) {

            Sheet sheet = workbook.getSheetAt(0);

            Row headerRow = sheet.getRow(0);
            if (headerRow == null) {
                return;
            }

            int colCount = headerRow.getLastCellNum();
            String[] columnNames = new String[colCount];
            for (int c = 0; c < colCount; c++) {
                Cell cell = headerRow.getCell(c);
                columnNames[c] = cell != null ? cell.toString() : "";
            }

            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columnNames, 0);

            for (int r = 1; r <= sheet.getLastRowNum(); r++) {
                Row row = sheet.getRow(r);
                Object[] rowData = new Object[colCount];
                if (row != null) {
                    for (int c = 0; c < colCount; c++) {
                        Cell cell = row.getCell(c);
                        if (cell != null) {
                            rowData[c] = switch (cell.getCellType()) {
                                case NUMERIC -> cell.getNumericCellValue();
                                case BOOLEAN -> cell.getBooleanCellValue();
                                default -> cell.toString();
                            };
                        }
                    }
                }
                model.addRow(rowData);
            }

            tbFileData.setModel(model);
            lbDisplayTotal.setText("จำนวนรายการ: " + model.getRowCount() + " แถว");
            styleTable();

        } catch (java.io.IOException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Failed to read Excel file", ex);
        }
    }

    private void styleTable() {
        tbFileData.setRowHeight(30);
        tbFileData.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13));
        tbFileData.setShowHorizontalLines(true);
        tbFileData.setShowVerticalLines(true);
        tbFileData.setGridColor(new java.awt.Color(220, 220, 220));
        tbFileData.setSelectionBackground(new java.awt.Color(0x2196F3));
        tbFileData.setSelectionForeground(java.awt.Color.WHITE);
        tbFileData.setIntercellSpacing(new java.awt.Dimension(1, 0));
        tbFileData.setFillsViewportHeight(true);

        javax.swing.table.JTableHeader header = tbFileData.getTableHeader();
        header.setFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 13));
        header.setBackground(new java.awt.Color(0x1565C0));
        header.setForeground(java.awt.Color.WHITE);
        header.setPreferredSize(new java.awt.Dimension(header.getWidth(), 35));
        header.setReorderingAllowed(false);

        tbFileData.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            private final java.awt.Color ODD_ROW  = new java.awt.Color(0xF0F6FF);
            private final java.awt.Color EVEN_ROW = java.awt.Color.WHITE;

            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13));
                if (!isSelected) {
                    setBackground(row % 2 == 0 ? EVEN_ROW : ODD_ROW);
                    setForeground(new java.awt.Color(0x212121));
                }
                setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 8));
                return this;
            }
        });
    }


    private void showDateSelected() {
        SpinnerDateModel dateModel = new SpinnerDateModel();
        JSpinner datePicker = new JSpinner(dateModel);
        datePicker.setEditor(new JSpinner.DateEditor(datePicker, "dd/MM/yyyy"));

        int option = JOptionPane.showConfirmDialog(
                this, datePicker, "Select Date",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (option == JOptionPane.OK_OPTION) {
            Date selected = (Date) datePicker.getValue();
            txtDocDate.setText(new SimpleDateFormat("dd/MM/yyyy").format(selected));
        }
    }


    private String getStringValue(javax.swing.table.DefaultTableModel model, int row, String colName) {
        for (int c = 0; c < model.getColumnCount(); c++) {
            if (model.getColumnName(c).equalsIgnoreCase(colName)) {
                Object val = model.getValueAt(row, c);
                return val != null ? val.toString() : "";
            }
        }
        return "";
    }

    private double getDoubleValue(javax.swing.table.DefaultTableModel model, int row, String colName) {
        for (int c = 0; c < model.getColumnCount(); c++) {
            if (model.getColumnName(c).equalsIgnoreCase(colName)) {
                Object val = model.getValueAt(row, c);
                if (val == null) return 0.0;
                if (val instanceof Number num) return num.doubleValue();
                try { return Double.parseDouble(val.toString()); }
                catch (NumberFormatException ignore) { return 0.0; }
            }
        }
        return 0.0;
    }

    /** ดึงค่า String จาก mapping แล้ว convert ด้วย ThaiUtil.Unicode2ASCII */
    private String mappedStr(javax.swing.table.DefaultTableModel model, int row,
                              Map<String, String> mapping, String field, String defaultVal) {
        String col = mapping.get(field);
        String val = (col != null) ? getStringValue(model, row, col) : defaultVal;
        return ThaiUtil.Unicode2ASCII(val);
    }

    /** ดึงค่า double จาก mapping หรือใช้ค่า default */
    private double mappedDbl(javax.swing.table.DefaultTableModel model, int row,
                              Map<String, String> mapping, String field, double defaultVal) {
        String col = mapping.get(field);
        return (col != null) ? getDoubleValue(model, row, col) : defaultVal;
    }

    // แปลง dd/MM/yyyy → yyyy-MM-dd สำหรับ MySQL
    private String toMysqlDate(String dateStr) {
        try {
            return new SimpleDateFormat("yyyy-MM-dd")
                    .format(new SimpleDateFormat("dd/MM/yyyy").parse(dateStr));
        } catch (ParseException ignore) {
            return dateStr;
        }
    }

    private void saveDataIntoDatabase() {
        if (!DatabaseConnection.isConnected()) {
            JOptionPane.showMessageDialog(this, "ไม่ได้เชื่อมต่อฐานข้อมูล", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String docNo   = txtDocumentNo.getText().trim();
        String docDate = txtDocDate.getText().trim();

        if (docNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "กรุณาระบุ Document Number", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) tbFileData.getModel();

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "ไม่มีข้อมูลใน Table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int totalRows = model.getRowCount();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "ต้องการบันทึกข้อมูล Document No: " + docNo + "\nจำนวน " + totalRows + " รายการ ใช่หรือไม่?",
                "ยืนยันการบันทึก",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        // --- Column mapping dialog ---
        String[] tableColumns = new String[model.getColumnCount()];
        for (int c = 0; c < model.getColumnCount(); c++) {
            tableColumns[c] = model.getColumnName(c);
        }
        ColumnMappingDialog mappingDialog = new ColumnMappingDialog(this, tableColumns);
        mappingDialog.setVisible(true);
        if (!mappingDialog.isConfirmed()) {
            return;
        }
        Map<String, String> columnMapping = mappingDialog.getMapping();

        // --- Progress dialog ---
        JDialog progressDialog = new JDialog(this, "กำลังบันทึกข้อมูล", true);
        progressDialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

        JProgressBar progressBar = new JProgressBar(0, totalRows);
        progressBar.setStringPainted(true);
        progressBar.setPreferredSize(new java.awt.Dimension(400, 28));

        JLabel statusLabel = new JLabel("เริ่มต้นการบันทึก...", javax.swing.SwingConstants.CENTER);

        JPanel panel = new JPanel(new java.awt.BorderLayout(0, 12));
        panel.setBorder(BorderFactory.createEmptyBorder(20, 24, 20, 24));
        panel.add(statusLabel, java.awt.BorderLayout.NORTH);
        panel.add(progressBar, java.awt.BorderLayout.CENTER);

        progressDialog.add(panel);
        progressDialog.pack();
        progressDialog.setLocationRelativeTo(this);

        // --- SwingWorker: DB บน background thread, update UI บน EDT ---
        SwingWorker<Void, Integer> worker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                Connection conn = DatabaseConnection.getConnection();
                try {
                    conn.setAutoCommit(false);

                    double total = 0;
                    for (int r = 0; r < model.getRowCount(); r++) {
                        total += mappedDbl(model, r, columnMapping, "R_Amount", 0.0);
                    }

                    String headerSql =
                        "INSERT INTO htranout (R_No, R_Date, R_Remark, R_Bran, R_Total, R_User, R_Post, R_UserPost, R_PostDate, R_PostTime) "
                      + "VALUES (?, ?, '', '', ?, '', 'N', '', null, '') "
                      + "ON DUPLICATE KEY UPDATE R_Date=VALUES(R_Date), R_Total=VALUES(R_Total)";

                    try (PreparedStatement ps = conn.prepareStatement(headerSql)) {
                        ps.setString(1, ThaiUtil.Unicode2ASCII(docNo));
                        ps.setString(2, toMysqlDate(docDate));
                        ps.setDouble(3, total);
                        ps.executeUpdate();
                    }

                    // R_No จาก form, R_Que auto-generate, R_Time=CURTIME(), R_EntryDate=CURDATE()
                    // R_Remark, R_RefCode, R_SendInterface, RefCode, R_Pqty = NULL
                    String detailSql =
                        "INSERT INTO tranout (R_No, R_Que, R_PCode, R_Stock, R_Pack, R_Qty, R_Post, R_Unit, R_Cost, R_Amount, R_TotalQty, R_User, R_Time, R_EntryDate, R_Remark, R_RefCode, R_SendInterface, RefCode, R_PName, R_Pqty) "
                      + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURTIME(), CURDATE(), NULL, NULL, NULL, NULL, ?, NULL) "
                      + "ON DUPLICATE KEY UPDATE "
                      + "  R_PCode=VALUES(R_PCode), R_Stock=VALUES(R_Stock), R_Pack=VALUES(R_Pack), "
                      + "  R_Qty=VALUES(R_Qty), R_Post=VALUES(R_Post), R_Unit=VALUES(R_Unit), "
                      + "  R_Cost=VALUES(R_Cost), R_Amount=VALUES(R_Amount), R_TotalQty=VALUES(R_TotalQty), "
                      + "  R_User=VALUES(R_User), R_PName=VALUES(R_PName)";

                    try (PreparedStatement ps = conn.prepareStatement(detailSql)) {
                        for (int r = 0; r < model.getRowCount(); r++) {
                            ps.setString(1,  ThaiUtil.Unicode2ASCII(docNo));
                            ps.setInt   (2,  r + 1);
                            ps.setString(3,  mappedStr(model, r, columnMapping, "R_PCode",    ""));
                            ps.setString(4,  mappedStr(model, r, columnMapping, "R_Stock",    ""));
                            ps.setDouble(5,  mappedDbl(model, r, columnMapping, "R_Pack",     1.0));
                            ps.setDouble(6,  mappedDbl(model, r, columnMapping, "R_Qty",      0.0));
                            ps.setString(7,  mappedStr(model, r, columnMapping, "R_Post",     "N"));
                            ps.setString(8,  mappedStr(model, r, columnMapping, "R_Unit",     ""));
                            ps.setDouble(9,  mappedDbl(model, r, columnMapping, "R_Cost",     0.0));
                            ps.setDouble(10, mappedDbl(model, r, columnMapping, "R_Amount",   0.0));
                            ps.setDouble(11, mappedDbl(model, r, columnMapping, "R_TotalQty", 0.0));
                            ps.setString(12, mappedStr(model, r, columnMapping, "R_User",     ""));
                            ps.setString(13, mappedStr(model, r, columnMapping, "R_PName",    ""));
                            ps.addBatch();
                            publish(r + 1);
                        }
                        ps.executeBatch();
                    }

                    conn.commit();

                } catch (SQLException ex) {
                    try { conn.rollback(); } catch (SQLException ignore) {}
                    throw ex;
                } finally {
                    try { conn.setAutoCommit(true); } catch (SQLException ignore) {}
                }
                return null;
            }

            @Override
            protected void process(List<Integer> chunks) {
                int current = chunks.get(chunks.size() - 1);
                progressBar.setValue(current);
                statusLabel.setText("กำลังบันทึก " + current + " / " + totalRows + " รายการ");
            }

            @Override
            protected void done() {
                progressDialog.dispose();
                try {
                    get();
                    JOptionPane.showMessageDialog(Main.this,
                            "บันทึกข้อมูลสำเร็จ " + totalRows + " รายการ",
                            "Success", JOptionPane.INFORMATION_MESSAGE);
                } catch (java.util.concurrent.ExecutionException ex) {
                    Throwable cause = ex.getCause();
                    if (cause == null) cause = ex;
                    logger.log(Level.SEVERE, "Failed to save data", cause);
                    JOptionPane.showMessageDialog(Main.this,
                            "เกิดข้อผิดพลาด: " + cause.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                    logger.log(Level.SEVERE, "Save operation interrupted", ex);
                }
            }
        };

        worker.execute();
        progressDialog.setVisible(true); // blocks EDT จนกว่า done() จะ dispose dialog
    }

    private void changeThemeApp() {
        String selected = (String) cbChangeTheme.getSelectedItem();
        try {
            javax.swing.LookAndFeel laf = switch (selected) {
                case "FlatDarkLaf"  -> new com.formdev.flatlaf.FlatDarkLaf();
                default             -> new com.formdev.flatlaf.FlatLightLaf();
            };
            javax.swing.UIManager.setLookAndFeel(laf);
            applyThaiFont();
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(Level.WARNING, "Cannot change theme", ex);
        }
    }

    private void closeApplication() {
        System.exit(0);
    }
}
